[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "resend", "twilio", "@netlify/blobs"]
  included_files = ["netlify/functions/**"]

[functions."stripe-webhook"]
  timeout = 26
