[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["@netlify/blobs", "resend", "nodemailer"]

# opzionale: lascia il plugin solo se lo usi davvero
[[plugins]]
package = "@netlify/plugin-lighthouse"
